<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <p><?php echo $this->translate('This is a'); ?></p>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            Testing
            asdadsas<br>
            saddadads
            asdadssaddas<br>
            saddasdas
        </div>
        <div class="col-lg-6">
            Testing 2
        </div>
    </div>
</div>
