<?php
$temperature = array();
$airPressure = array();
$humidity = array();
$battery = array();
$labels = array();
$i = 1;

foreach ($this->feed as $measure) {
    array_push($temperature, $measure->field1);
    array_push($airPressure, $measure->field2);
    array_push($humidity, $measure->field3);
    array_push($battery, $measure->field4);
    array_push($labels, $i);
    $i++;
}
?>

<div class="row">
    <div class="col-lg-12">
        <button class="thingsspeak-data" id="temperature"><?php echo $this->translate('Temperature'); ?></button>
        <button class="thingsspeak-data" id="airPressure"><?php echo $this->translate('Air pressure'); ?></button>
        <button class="thingsspeak-data" id="humidity"><?php echo $this->translate('Humidity'); ?></button>
        <button class="thingsspeak-data" id="battery"><?php echo $this->translate('Battery'); ?></button>
        <p></p>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Line Chart Visualization'); ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p id="data-type"></p>
                <div style="width:80%">
                    <div>
                        <canvas id="canvas" height="250" width="350"></canvas>
                    </div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

<script type="application/javascript">
    var temperature = <?php echo json_encode($temperature); ?>;
    var airPressure = <?php echo json_encode($airPressure); ?>;
    var humidity = <?php echo json_encode($humidity); ?>;
    var battery = <?php echo json_encode($battery); ?>;

    var data = temperature;
    var labels = <?php echo json_encode($labels); ?>;
</script>
